#!/bin/bash

# Claude usage plugin for SketchyBar.
#
# Shows how full the two Claude plan windows are, "5h 86% · 7d 25%", so a
# heavy refactor can be timed for after a reset instead of hitting the wall
# halfway through. The numbers come from `dotfiles agent usage --bar`, which
# owns the credentials lookup, the endpoint call and a 60s cache; this file
# only paints. The item hides itself when there is no Claude Code login, and
# a click (argument "notify") posts a notification with the reset times.

# Sketchybar spawns plugins from the bar daemon's own environment, so the
# `export`s in sketchybarrc do NOT reach them. colors.sh carries the same
# palette as a standalone file and is regenerated by apply-theme.sh, so
# switching themes recolours these items too.
# shellcheck source=/dev/null
[ -f "$HOME/.config/sketchybar/colors.sh" ] && . "$HOME/.config/sketchybar/colors.sh"

# Fallbacks keep the item readable if colors.sh is missing (fresh clone
# before a theme has ever been applied) rather than rendering colourless.
RED="${RED:-0xffff6767}"
YELLOW="${YELLOW:-0xffffca85}"
GREY="${GREY:-0xff8a8a8a}"
WHITE="${WHITE:-0xffedecee}"

# ~/bin is where `dotfiles doctor` links the commands; before that has run
# the plugin still works from the checkout it was symlinked out of.
USAGE="$HOME/bin/dotfiles-agent-usage"
[ -x "$USAGE" ] || USAGE="$(dirname "$(readlink -f "$0")")/../../../bin/dotfiles-agent-usage"

if [ "${1:-}" = "notify" ]; then
    "$USAGE" --notify --refresh
    exit 0
fi

OUT="$("$USAGE" --bar 2>/dev/null)" || OUT=""

# No login (or nothing cached and the endpoint is down): no item rather than
# a permanent question mark.
if [ -z "$OUT" ]; then
    sketchybar --set "$NAME" drawing=off
    exit 0
fi

LABEL="${OUT%%	*}"
LEVEL="${OUT##*	}"

case "$LEVEL" in
    critical) COLOR=$RED ;;
    warning) COLOR=$YELLOW ;;
    stale) COLOR=$GREY ;;
    *) COLOR=$WHITE ;;
esac

sketchybar --set "$NAME" drawing=on label="$LABEL" label.color="$COLOR" icon.color="$COLOR"
