#!/bin/bash
# Generated by `dotfiles theme` from themes/{{ theme_name }}/colors.toml — do not edit.
# Sourced by bordersrc. ARGB: 0xAARRGGBB.
BORDERS_ACTIVE_COLOR={{ accent_argb }}
BORDERS_INACTIVE_COLOR={{ muted_argb }}
BORDERS_BACKGROUND_COLOR=0x30{{ background_strip }}
