# Generated by `dotfiles theme` from themes/{{ theme_name }}/colors.toml — do not edit.
export FZF_THEME_COLORS="--color=fg:{{ foreground }},bg:{{ background }},hl:{{ orange }},fg+:{{ foreground }},bg+:{{ selection }},hl+:{{ orange }},info:{{ accent }},prompt:{{ cyan }},pointer:{{ purple }},marker:{{ green }},spinner:{{ purple }},header:{{ muted }}"
