# Generated by `dotfiles theme` from themes/{{ theme_name }}/colors.toml — do not edit.
# Merged after ~/.config/lazygit/config.yml via LG_CONFIG_FILE.
gui:
  theme:
    lightTheme: {{ is_light }}
    activeBorderColor:
      - '{{ accent }}'
      - bold
    inactiveBorderColor:
      - '{{ muted }}'
    selectedLineBgColor:
      - '{{ lighter_background }}'
    optionsTextColor:
      - '{{ blue }}'
    searchingActiveBorderColor:
      - '{{ yellow }}'
      - bold
