# Generated by `dotfiles theme` from themes/{{ theme_name }}/colors.toml — do not edit.
user: {{ accent_strip }}
group: {{ muted_strip }}
permission:
  read: {{ green_strip }}
  write: {{ yellow_strip }}
  exec: {{ red_strip }}
  exec-sticky: {{ red_strip }}
  no-access: {{ muted_strip }}
date:
  hour-old: {{ foreground_strip }}
  day-old: {{ blue_strip }}
  older: {{ muted_strip }}
size:
  none: {{ muted_strip }}
  small: {{ green_strip }}
  medium: {{ yellow_strip }}
  large: {{ orange_strip }}
tree-edge: {{ muted_strip }}
links:
  valid: {{ green_strip }}
  invalid: {{ red_strip }}
inode:
  valid: {{ purple_strip }}
  invalid: {{ red_strip }}
