-- Generated by `dotfiles theme` — do not edit.
-- Read by .config/nvim/lua/plugins/astroui.lua (colorscheme) and
-- .config/nvim/lua/plugins/theme.lua (which dofile()s plugin_spec).
return {
  name = "{{ theme_name }}",
  colorscheme = "{{ nvim_colorscheme }}",
  plugin_spec = "{{ nvim_plugin_spec }}",
  colors = {
    background = "{{ background }}",
    foreground = "{{ foreground }}",
    accent = "{{ accent }}",
    muted = "{{ muted }}",
  },
}
