-- Generated by `dotfiles theme` — do not edit.
-- Read by .config/nvim/lua/plugins/astroui.lua (colorscheme) and
-- .config/nvim/lua/plugins/theme.lua (which dofile()s plugin_spec).
return {
  name = "{{ theme_name }}",
  colorscheme = "{{ nvim_colorscheme }}",
  plugin_spec = "{{ nvim_plugin_spec }}",
  mode = "{{ mode }}",
  colors = {
    background = "{{ background }}",
    dark_background = "{{ dark_background }}",
    darker_background = "{{ darker_background }}",
    lighter_background = "{{ lighter_background }}",
    selection = "{{ selection }}",
    foreground = "{{ foreground }}",
    dark_foreground = "{{ dark_foreground }}",
    light_foreground = "{{ light_foreground }}",
    bright_foreground = "{{ bright_foreground }}",
    accent = "{{ accent }}",
    muted = "{{ muted }}",
    red = "{{ red }}",
    orange = "{{ orange }}",
    yellow = "{{ yellow }}",
    green = "{{ green }}",
    cyan = "{{ cyan }}",
    blue = "{{ blue }}",
    magenta = "{{ magenta }}",
    purple = "{{ purple }}",
    brown = "{{ brown }}",
  },
}
