#!/bin/bash
# Generated by `dotfiles theme` from themes/{{ theme_name }}/colors.toml — do not edit.
# Sourced by sketchybarrc and by every plugin (plugins do not inherit the
# bar's environment). ARGB: 0xAARRGGBB.
export BLACK={{ background_argb }}
export WHITE={{ foreground_argb }}
export RED={{ red_argb }}
export GREEN={{ green_argb }}
export BLUE={{ blue_argb }}
export YELLOW={{ yellow_argb }}
export ORANGE={{ orange_argb }}
export MAGENTA={{ magenta_argb }}
export GREY={{ muted_argb }}
export TRANSPARENT=0x00000000
export BAR_COLOR={{ background_argb }}
export ITEM_BG_COLOR={{ lighter_background_argb }}
export ACCENT_COLOR={{ accent_argb }}
