-- Generated by `dotfiles theme` from themes/{{ theme_name }}/colors.toml — do not edit.
-- Loaded by ~/.wezterm.lua via pcall(dofile, ...); returns a `config.colors` table.
return {
  foreground = '{{ foreground }}',
  background = '{{ background }}',
  cursor_bg = '{{ accent }}',
  cursor_fg = '{{ background }}',
  cursor_border = '{{ accent }}',
  selection_fg = '{{ selection_foreground }}',
  selection_bg = '{{ selection }}',
  ansi = {
    '{{ black }}', '{{ red }}', '{{ green }}', '{{ yellow }}',
    '{{ blue }}', '{{ magenta }}', '{{ cyan }}', '{{ white }}',
  },
  brights = {
    '{{ bright_black }}', '{{ bright_red }}', '{{ bright_green }}', '{{ bright_yellow }}',
    '{{ bright_blue }}', '{{ bright_magenta }}', '{{ bright_cyan }}', '{{ bright_white }}',
  },
  tab_bar = {
    background = '{{ dark_background }}',
    active_tab = { bg_color = '{{ accent }}', fg_color = '{{ background }}' },
    inactive_tab = { bg_color = '{{ background }}', fg_color = '{{ muted }}' },
    inactive_tab_hover = { bg_color = '{{ selection }}', fg_color = '{{ foreground }}' },
    new_tab = { bg_color = '{{ background }}', fg_color = '{{ accent }}' },
    new_tab_hover = { bg_color = '{{ selection }}', fg_color = '{{ accent }}' },
  },
}
