// Generated by `dotfiles theme` from themes/{{ theme_name }}/colors.toml — do not edit.
// config.kdl always selects `theme "dotfiles"`; only this file changes.
themes {
    dotfiles {
        fg "{{ foreground }}"
        bg "{{ background }}"
        black "{{ black }}"
        red "{{ red }}"
        green "{{ green }}"
        yellow "{{ yellow }}"
        blue "{{ blue }}"
        magenta "{{ magenta }}"
        cyan "{{ cyan }}"
        white "{{ white }}"
        orange "{{ orange }}"
    }
}
