#!/bin/bash

# SketchyBar Configuration
# Minimal, beautiful menu bar with Aerospace integration

# THEME_COLORS_START
export BLACK=0xff1a1b26
export WHITE=0xffc0caf5
export RED=0xfff7768e
export GREEN=0xff9ece6a
export BLUE=0xff7aa2f7
export YELLOW=0xffe0af68
export ORANGE=0xffff9e64
export MAGENTA=0xffbb9af7
export GREY=0xff565f89
export TRANSPARENT=0x00000000
export BAR_COLOR=0xff1a1b26
export ITEM_BG_COLOR=0xff24283b
export ACCENT_COLOR=$BLUE
# THEME_COLORS_END

##### Bar Appearance #####
sketchybar --bar \
    height=32 \
    color=$BAR_COLOR \
    border_width=0 \
    shadow=on \
    sticky=on \
    padding_left=10 \
    padding_right=10

##### Changing Defaults #####
sketchybar --default \
    icon.font="Hack Nerd Font:Bold:14.0" \
    icon.color=$WHITE \
    icon.padding_left=4 \
    icon.padding_right=4 \
    label.font="Hack Nerd Font:Bold:13.0" \
    label.color=$WHITE \
    label.padding_left=4 \
    label.padding_right=4 \
    background.padding_left=4 \
    background.padding_right=4

##### Adding Left Items #####

# Aerospace Workspaces
sketchybar --add event aerospace_workspace_change \
           --add item aerospace.workspaces left \
           --set aerospace.workspaces \
                 icon= \
                 script="$HOME/.config/sketchybar/plugins/aerospace.sh" \
                 background.color=$ITEM_BG_COLOR \
                 background.corner_radius=5 \
                 background.height=24 \
           --subscribe aerospace.workspaces aerospace_workspace_change

##### Adding Right Items #####

# Clock
sketchybar --add item clock right \
           --set clock \
                 update_freq=10 \
                 icon= \
                 script="$HOME/.config/sketchybar/plugins/clock.sh" \
                 background.color=$ITEM_BG_COLOR \
                 background.corner_radius=5 \
                 background.height=24

# Battery
sketchybar --add item battery right \
           --set battery \
                 update_freq=120 \
                 icon= \
                 script="$HOME/.config/sketchybar/plugins/battery.sh" \
                 background.color=$ITEM_BG_COLOR \
                 background.corner_radius=5 \
                 background.height=24

##### Finalizing Setup #####
sketchybar --update
