[tools]
elixir = "latest"
erlang = "latest"
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
yarn = "latest"
java = "temurin-17"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
